<?php

use Beshkin\MicloudPhp\Helpers\Helper;
use Beshkin\MicloudPhp\MiCloud\MiCloudClient;
use PHPUnit\Framework\TestCase;

class MiCloudTests extends TestCase
{
    private $config;

    public function setUp(): void
    {
        $dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../');
        $dotenv->load();

        $this->config = [
            'country' => $_ENV['MI_CLOUD_COUNTRY'],
            'login' => $_ENV['MI_CLOUD_LOGIN'],
            'password' => $_ENV['MI_CLOUD_PASSWORD'],
        ];
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSwitchOn()
    {
        $client = new MiCloudClient($this->config);
        $client->login();
        $result = $client->miioCall(
            $_ENV['MI_CLOUD_DEVICE'],
            'set_power',
            Helper::withLightEffect('on', 5)
        );

        $this->assertNotNull($result);
        $this->assertTrue($result->message == 'ok');
    }
}